const portfolios = [
  {
    id: 1,
    title: 'Smanda iLearn - Learning Management System App',
    img: '/smanda-ilearn/landing-page-crop.png',
    githubLink: 'https://github.com/bayuhadi863/elearning-app',
    time: 'Oct 2023 - Dec 2023',
    member: 'Bayu Hadi Leksana',
    tech: ['React JS', 'Tailwind CSS', 'Laravel', 'MySQL'],
    description: `Smanda iLearn is a web-based Learning Management System application. The purpose of this application is to manage (upload, view, download, and perform CRUD operations on) learning materials, assignments, quizzes, and grades. This application has 3 roles: Admin, Student, and Teacher. Admins have the right to manage the application's core data. Teachers have the right to upload materials and assignments and create quizzes. Students have the right to view materials and assignments and submit assignments.`,
    images: [
      '/smanda-ilearn/landing-page-full.png',
      '/smanda-ilearn/login.png',
      '/smanda-ilearn/admin/dashboard.png',
      '/smanda-ilearn/admin/teachers-table.png',
      '/smanda-ilearn/admin/teacher-detail.png',
      '/smanda-ilearn/admin/edit-teacher.png',
      '/smanda-ilearn/admin/delete-teacher.png',
      '/smanda-ilearn/admin/create-student.png',
      '/smanda-ilearn/admin/classes-table.png',
      '/smanda-ilearn/admin/create-class.png',
      '/smanda-ilearn/admin/class-detail.png',
      '/smanda-ilearn/admin/create-edit-teacher.png',
      '/smanda-ilearn/admin/create-season.png',
      '/smanda-ilearn/admin/create-subject.png',
      '/smanda-ilearn/admin/edit-class.png',
      '/smanda-ilearn/admin/profile.png',
      '/smanda-ilearn/admin/seasons-table.png',
      '/smanda-ilearn/admin/subjects-table.png',
      '/smanda-ilearn/teacher/assignment-detail.png',
      '/smanda-ilearn/teacher/assignments-list.png',
      '/smanda-ilearn/teacher/class-detail.png',
      '/smanda-ilearn/teacher/classes-list.png',
      '/smanda-ilearn/teacher/create-materi.png',
      '/smanda-ilearn/teacher/create-quiz.png',
      '/smanda-ilearn/teacher/create-tugas.png',
      '/smanda-ilearn/teacher/dashboard.png',
      '/smanda-ilearn/teacher/edit-materi.png',
      '/smanda-ilearn/teacher/edit-profile.png',
      '/smanda-ilearn/teacher/give-score.png',
      '/smanda-ilearn/teacher/make-questions.png',
      '/smanda-ilearn/teacher/materi-detail.png',
      '/smanda-ilearn/teacher/materi-list.png',
      '/smanda-ilearn/teacher/quizzez-list.png',
      '/smanda-ilearn/teacher/view-assignment-submit.png',
      '/smanda-ilearn/student/assignment-detail.png',
      '/smanda-ilearn/student/assignments-list.png',
      '/smanda-ilearn/student/average-score.png',
      '/smanda-ilearn/student/dashboard.png',
      '/smanda-ilearn/student/do-quiz.png',
      '/smanda-ilearn/student/materi-document-detail.png',
      '/smanda-ilearn/student/materi-document-list.png',
      '/smanda-ilearn/student/materi-video-list.png',
      '/smanda-ilearn/student/materi-video-detail.png',
      '/smanda-ilearn/student/score-chart.png',
      '/smanda-ilearn/student/subject-detail.png',
      '/smanda-ilearn/student/subjects-list.png',
      '/smanda-ilearn/student/submit-assignment.png',
    ],
    videoDemoLink: 'https://youtu.be/iMZPqjqO2PI?si=vF07-ddzU1PxzwU_',
  },
  {
    id: 2,
    title: 'Job Finder - Job Application Web App',
    img: '/job-finder/landing-page-crop.png',
    githubLink: 'https://github.com/bayuhadi863/job-vacancy-app',
    time: 'July 2023',
    member: 'Bayu Hadi, H. Johnston, M. Yanur Ghoffaar',
    tech: ['HTML', 'CSS', 'Bootstrap', 'Laravel', 'MySQL'],
    description: `Job Finder is a web-based application that allows users to search and apply for jobs. The application has two roles: Admin and User. The Admin is responsible for managing the application's core data. Users have the right to search for and apply for jobs.`,
    images: [
      '/job-finder/landing-page-full.png',
      '/job-finder/login.png',
      '/job-finder/register.png',
      '/job-finder/user/application-history.png',
      '/job-finder/user/create-edit-cv.png',
      '/job-finder/user/create-edit-education.png',
      '/job-finder/user/create-edit-experience.png',
      '/job-finder/user/job-detail.png',
      '/job-finder/user/job-list.png',
      '/job-finder/user/view-cv.png',
      '/job-finder/admin/applicant-detail.png',
      '/job-finder/admin/applicants-table.png',
      '/job-finder/admin/categories-table.png',
      '/job-finder/admin/category-detail.png',
      '/job-finder/admin/create-category.png',
      '/job-finder/admin/create-job.png',
      '/job-finder/admin/create-user.png',
      '/job-finder/admin/dashboard.png',
      '/job-finder/admin/edit-category.png',
      '/job-finder/admin/edit-job.png',
      '/job-finder/admin/edit-user.png',
      '/job-finder/admin/job-detail.png',
      '/job-finder/admin/jobs-table.png',
      '/job-finder/admin/users-table.png',
    ],
    videoDemoLink: 'https://youtu.be/kvXeSa16EXg?si=we-hG7EwYXJWEnFZ',
  },
  {
    id: 3,
    title: 'Movie App using TMDB API',
    img: '/react-movie/home-crop.png',
    githubLink: 'https://github.com/bayuhadi863/react-movie-app',
    time: 'Aug 2027',
    member: 'Bayu Hadi Leksana',
    tech: ['React JS', 'Bootstrap', 'TMDB API'],
    description:
      'This is an application that functions to display a list of movies from the The Movie DB API. Users can see the list of movies by several categories. The application displays movie data in real time and is always updated. The application is an implementation of the use of public API.',
    images: ['/react-movie/home-full.png', '/react-movie/trending.png', '/react-movie/upcoming.png'],
    videoDemoLink: null,
  },
  {
    id: 4,
    title: 'Scholar Gate - Scholarship Registration App',
    img: '/scholar-gate/landing-page-crop.png',
    githubLink: 'https://github.com/bayuhadi863/scholarship-registration-app',
    time: 'May 2023',
    member: 'Bayu Hadi Leksana',
    tech: ['HTML', 'CSS', 'Bootstrap', 'PHP', 'MySQL'],
    description: `Scholar Gate is a web app that allows users to search and apply for scholarships. It has two roles: Admin and User. Admins manage the app's core data. Users can search and apply for scholarships.`,
    images: [
      '/scholar-gate/landing-page-full.png',
      '/scholar-gate/login.png',
      '/scholar-gate/register.png',
      '/scholar-gate/user/profil-user.png',
      '/scholar-gate/user/riwayat_pendaftaran_beasiswa.png',
      '/scholar-gate/user/riwayat-pesan.png',
      '/scholar-gate/user/scholarship-page.png',
      '/scholar-gate/admin/admin-dashboard.png',
      '/scholar-gate/admin/detail-pengguna.png',
      '/scholar-gate/admin/edit-beasiswa.png',
      '/scholar-gate/admin/edit-profil-admin.png',
      '/scholar-gate/admin/tabel-beasiswa.png',
      '/scholar-gate/admin/tabel-pendaftaran-beasiswa.png',
      '/scholar-gate/admin/tabel-pengguna.png',
      '/scholar-gate/admin/tabel-pesan.png',
      '/scholar-gate/admin/tambah-beasiswa.png',
    ],
    videoDemoLink: 'https://youtu.be/BMhWTpyRNIU?si=xFieGECujdh7y1po',
  },
];

const sosmedLinks = [
  {
    name: 'Instagram',
    href: 'https://www.instagram.com/bayuhadileksana?igsh=YTQwZjQ0NmI0OA==',
  },
  {
    name: 'Whatsapp',
    href: 'https://wa.link/397fy7',
  },
  {
    name: 'Telegram',
    href: 'https://t.me/Bayuhl',
  },
  {
    name: 'Linkedin',
    href: 'https://www.linkedin.com/in/bayu-hadi-leksana/',
  },
  {
    name: 'Github',
    href: 'https://github.com/bayuhadi863',
  },
];

export { portfolios, sosmedLinks };
